### ISSUE TITLE
llvmpipe does not perform the side effecting switch operation

### ISSUE THREAD

**Issue by AaronGhost** [AaronGhost/glslsmith-bugs-tracker#4]
# Description

The following code containing a switch case does not seem to execute the side-effecting operation in the switch statement.
```glsl
#version 310 es
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(std430, binding = 0) buffer buffer_0 {
 uint ext_0; // 0
 uint ext_1; // 5
 uint ext_2; // 0
} ;
void main()
{
  ext_0 += ext_1; // ext_0 = 5
  switch(ext_1 ^= ext_0) // ext_0 = 5 ^ 5 = 0
  {
    case 0u:
      ext_2 = 1u;
      break;
    case 5u:
      ext_2 = 2u;
      break;
  }
}
```
# llvmpipe output:
```
buffer_0 5 5 2
```

# Expected output:
```
buffer_0 5 0 1
```

# Thinking process:
* The first line affects the value ext_0 = 5
* The second line affects the ext_1 with xor ext_0 so ext_1 = 0

# Code link
For the related code in the shadertrap test format, see:  [llvmpipe/miscompilation/shader04.shadertrap](../blob/master/llvmpipe/miscompilation/shader04.shadertrap)

**Comment by afd** [comment]
"containing an empty switch body" isn't right in the description, since this one has a switch body.

**Comment by AaronGhost** [comment]
Reported an equivalent version to the Mesa project with integers instead of unsigned integers:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/5185

**Comment by AaronGhost** [comment]
Fixed in less than 24h, the bug has been already reported once in 2011. The shader_test will be added to the tests for piglits.
